name: CI_Typecheck

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Install Deps
      run: npm install
      working-directory: client
    
    - name: Run Typecheck
      run: npm run type-check
      working-directory: client   
